services:
  - type: web
    name: brain-tumor-detection
    env: python
    rootDir: Brain_Tumor_Detection
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
    plan: starter

