services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --preload app:app
    envVars:
      - key: PORT
        value: 5000
    plan: starter

