services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: cd Brain_Tumor_Detection && pip install -r requirements.txt
    startCommand: cd Brain_Tumor_Detection && gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
    plan: starter

